{% set name = "cockroachdb" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc36de86bdf8b56b24c6b556b0eaf20b7dd6e6a1cd73addd31c0ccc4c99639a2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools
    - psycopg2
    - sqlalchemy

test:
  imports:
    - cockroachdb
    - cockroachdb.sqlalchemy

about:
  home: https://github.com/cockroachdb/cockroachdb-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: CockroachDB adapter for SQLAlchemy
  doc_url: https://pypi.org/project/cockroachdb/
  dev_url: https://github.com/cockroachdb/cockroachdb-python

extra:
  recipe-maintainers:
    - mwilson8
    - rluria14
    - benhuff
